### ISSUE TITLE
In seq2seq pytorchTypeError: 'int' object is not callable in attention is all you need notebook

### ISSUE THREAD

**Issue by VinACE** [bentrevett/pytorch-seq2seq#129]
I am trying to get a output of int values
	if __name__ == "__main__":
		device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
		INPUT_DIM = 10
		OUTPUT_DIM = 10
		src_vocab_size = 10
		trg_vocab_size = 10
		
		SRC_PAD_IDX = 0
		TRG_PAD_IDX = 0

		x = torch.tensor([[1, 5, 6, 4, 3, 9, 5, 2, 0, 0], [1, 8, 7, 3, 4, 5, 6, 7, 2, 0]]).to(
			device
		)
		trg =  torch.tensor([[1, 7, 4, 3, 5, 9, 2, 0,0,0], [1, 5, 6, 2, 4, 7, 6, 2,0,0]]).to(device)
		model = Seq2Seq(src_vocab_size, trg_vocab_size, SRC_PAD_IDX, TRG_PAD_IDX, device).to(
			device
		)
		out, attention = model(x, trg[:, :-1])
		print(out.shape)
		print(attention.shape)

getting following error,
Traceback (most recent call last):
  File "VASNet/seq_sum.py", line 477, in <module>
    out, attention = model(x, trg[:, :-1])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "***/seq_sum.py", line 386, in forward
    enc_src = self.encoder(src, src_mask)
TypeError: 'int' object is not callable

can you help me what should do to overcome this error, will the seq2seq not accept numeric input

**Comment by VinACE** [comment]
# issue was with my model definition. corrected as below.
    model = Seq2Seq(enc, dec, SRC_PAD_IDX, TRG_PAD_IDX, device).to(
        device
    )
    out, attention = model(x, trg[:, :-1])
    print(out.shape)
    print(attention.shape)
